/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_79e634f3 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/triqzrteonlvxkhzdiyb/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    console.error('Missing Supabase environment variables:', { 
      hasUrl: !!url, 
      hasKey: !!key 
    });
    throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables are required');
  }
  
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client()
    if (!supabase) {
      throw new Error('Failed to create Supabase client - check environment variables');
    }
    
    const { error } = await supabase.from("kv_store_79e634f3").upsert({
      key,
      value
    });
    
    if (error) {
      console.error('KV Store set error:', error);
      throw new Error(`KV Store set failed: ${error.message}`);
    }
  } catch (error: any) {
    console.error('KV Store set exception:', error);
    throw new Error(`KV Store set exception: ${error.message}`);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_79e634f3").select("value").eq("key", key).maybeSingle();
    if (error) {
      console.error('KV Store get error:', error);
      throw new Error(`KV Store get failed: ${error.message}`);
    }
    return data?.value;
  } catch (error: any) {
    console.error('KV Store get exception:', error);
    throw new Error(`KV Store get exception: ${error.message}`);
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_79e634f3").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_79e634f3").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_79e634f3").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_79e634f3").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_79e634f3").select("key, value").like("key", prefix + "%");
    if (error) {
      console.error('KV Store getByPrefix error:', error);
      throw new Error(`KV Store getByPrefix failed: ${error.message}`);
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error: any) {
    console.error('KV Store getByPrefix exception:', error);
    throw new Error(`KV Store getByPrefix exception: ${error.message}`);
  }
};